language: r
dist: trusty

sudo: true
cache: 
  - packages
  - /tmp/texlive
  - /$HOME/.texlive
warnings_are_errors: false

r_packages:
 - assertthat
 - bitops
 - chron
 - colorspace
 - cowplot
 - crayon
 - curl
 - data.table
 - DBI
 - devtools
 - digest
 - dtplyr
 - evaluate
 - forecast
 - formatR
 - fracdiff
 - ggplot2
 - git2r
 - grattan
 - gridExtra
 - gtable
 - httr
 - knitr
 - labeling
 - lattice
 - lazyeval
 - lubridate
 - magrittr
 - memoise
 - munsell
 - nnet
 - plyr
 - quadprog
 - R6
 - Rcpp
 - RCurl
 - readr
 - readxl
 - reshape2
 - rsconnect
 - rsdmx
 - rstudioapi
 - scales
 - showtext
 - showtextdb
 - stringi
 - stringr
 - sysfonts
 - taxstats
 - testthat
 - tibble
 - tidyr
 - timeDate
 - tseries
 - withr
 - XML
 - xtable
 - zoo

r_github_packages:
  - hughparsonage/taxstats
  - hughparsonage/grattanCharts
  - yixuan/showtext


before_install:
  - source ./source/texlive.sh
  - tlmgr install acronym bigfoot blindtext chngcntr cmap nowidow mdframed navigator needspace tablefootnote tocloft xpatch multirow bbding mathastext isomath relsize
  - tlmgr update --all
  - sudo apt-get update
  - sudo apt-get install texlive-bibtex-extra

install: echo Installation step #do not remove this line!

before_script:
    # as somehow no biber package is available for ubuntu 12.04 via apt, let's just download it directly
    # - wget "http://downloads.sourceforge.net/project/biblatex-biber/biblatex-biber/0.9.9/binaries/Linux/biber-linux_x86_64.tar.gz"
  - wget "https://sourceforge.net/projects/biblatex-biber/files/biblatex-biber/current/binaries/Linux/biber-linux_x86_64.tar.gz"
  - tar xzf biber-linux_x86_64.tar.gz
  - export PATH=$PATH:$PWD
  - tlmgr update biber
  - sudo apt-get install -y r-cran-dplyr
  - Rscript -e "if (!requireNamespace('devtools', quietly = TRUE)) install.packages('devtools')"
  #- Rscript -e "if (!requireNamespace('dplyr', quietly = TRUE) || packageVersion('dplyr') != package_version('0.5.0')) devtools::install_version('dplyr', version = '0.5.0', repos = 'http://cran.us.r-project.org')"
  #- Rscript -e "if (!requireNamespace('dtplyr', quietly = TRUE) || packageVersion('dtplyr') != package_version('0.0.2')) devtools::install_version('dtplyr', version = '0.0.2', repos = 'http://cran.us.r-project.org')"
  - Rscript -e "if (!requireNamespace('grattan', quietly = TRUE)) install.packages('grattan', dep = TRUE)"
  - Rscript -e "if (!requireNamespace('grattanCharts', quietly = TRUE)) devtools::install_github('hughparsonage/grattanCharts')"
  - Rscript -e "if (!requireNamespace('taxstats', quietly = TRUE)) devtools::install_github('hughparsonage/taxstats')"
  - Rscript -e "if (!requireNamespace('showtext', quietly = TRUE)) devtools::install_github('yixuan/showtext')"
  - Rscript -e "if (!requireNamespace('knitr', quietly = TRUE)) install.packages('knitr')"
  - Rscript -e "if (!requireNamespace('readxl', quietly = TRUE)) install.packages('readxl')"
  - Rscript -e "if (!requireNamespace('testthat', quietly = TRUE)) install.packages('testthat')"
  - Rscript -e "if (!requireNamespace('cowplot', quietly = TRUE)) install.packages('cowplot')"
  - Rscript -e "if (!requireNamespace('tidyr', quietly = TRUE)) install.packages('tidyr')"
  - Rscript R/portability.R

script:
  - set -e
  - Rscript -e "knitr::knit('Assessing-the-2016-super-tax-reforms.Rnw')"
  - pdflatex -draftmode -halt-on-error Assessing-the-2016-super-tax-reforms.tex
  - biber Assessing-the-2016-super-tax-reforms
  - Rscript CheckBiber.R
  - pdflatex -draftmode Assessing-the-2016-super-tax-reforms.tex

notifications:
  email: false
